export const Types = {
    START_FETCH_PRODUCTS: 'START_FETCH_PRODUCTS',
    END_FETCH_PRODUCTS: 'END_FETCH_PRODUCTS',

    START_FETCH_PRODUCT: 'START_FETCH_PRODUCT',
    END_FETCH_PRODUCT: 'END_FETCH_PRODUCT',
    
    START_FETCH_CATEGORIES: 'START_FETCH_CATEGORIES',
    END_FETCH_CATEGORIES: 'END_FETCH_CATEGORIES'
}